language: php
php:
  - 7.0
# - 5.6
# - hhvm

before_install:
  - pecl install ast
  - echo "extension=ast.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer self-update
  - composer install --dev

script:
  - ./vendor/bin/phpunit --verbose

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
